func = lambda s: (ord(s[0]) == 65 or ord(s[0]) == 97) and (ord(s[-1]) == 65 or ord(s[-1]) == 97)
print(func('abcd'))
print(func('bcda'))
print(func('abcda'))
print(func('Abcd'))
print(func('bcdA'))
print(func('abcdA'))
